stages:
  - containerization

services: 
    - name: docker:latest

containerization:
  stage: containerization # must match the stage name declared above
  script:
    # Build the container image
    - docker build -t devnik/devnik-api .
    # Push the container image to the registry
    - docker push devnik/devnik-api
    # Cleanup by removing the local image
    - docker image rm devnik/devnik-api